config/routes.rb
Rails.application.routes.draw do
  match '/logout', to: 'sessions#destroy', via: :delete
   root 'sessions#index'
   post 'sessions/new', to: 'sessions#create'
   post 'events/new', to: 'events#create'
   resources :users, only: [:new,:create,:show]
   resources :events, only: [:index,:show,:new]
   resources :sessions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :creator, :class_name => 'User', :foreign_key => 'user_id'
  has_many :organizers
    has_many :attendees,:through => :organizers,:source => :user

scope :upcoming_events, ->{ where("event_date > ?", Time.now)  }
scope :previous_events, ->{ where("event_date > ?", Time.now)  }

#class methods into scopes!!!
    # def self.upcoming_events
    #   Event.all.where("event_date > ?", Time.now)
    # end

    # def self.previous_events
    #   Event.all.where("event_date < ?", Time.now)
    # end


end

app/models/organizer.rb
class Organizer < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
   has_many :events
    has_many :organizers
    has_many :attended_events,:through => :organizers,:source => :event




    def self.upcoming_events user
      user.events.where("event_date > ?", Time.now)
    end

    def self.previous_events user
      user.events.where("event_date < ?", Time.now)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



  def log_in(user)
    cookies[:user_id] = user.id
  end
helper_method :log_in,:current_user,:log_out

def log_out(user)
  cookies.delete(:user_id)
  @current_user = nil
end

  def current_user
@current_user ||= User.find_by(id:cookies[:user_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @event = Event.all
    @upcoming_events = Event.upcoming_events
    @previous_events = Event.previous_events
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find_by(id: params[:id])
  end

  def create
    @user = User.find_by(id: cookies[:user_id])
    event = @user.events.build(event_params)
    if event.save
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def event_params
    params.require(:event).permit(:event_date, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index

  end
  def create
    user = User.find_by(name: params[:sessions][:name])
  if user
    log_in user
    redirect_to user
  else
    render 'new'
  end
  end

  def destroy
  user = User.find_by(id:cookies[:user_id])
    current_user
    log_out user
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id])

    @upcoming_events = User.upcoming_events @user
    @previous_events = User.previous_events @user
  end

  def create
    @user = User.new(user_params)

    if @user.save
    
      PrivateEventMailer.with(user: @user).welcome_email.deliver_later
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Events Index</h1>   <p><%= link_to "Home", root_path %></p> <p><%= link_to "New Event", new_event_path %></p>


<h3>Upcoming Events</h3>

<% @event.upcoming_events.each do |u| %>

<h4>Event host :</h4> <%=u.creator.name%>

<h4>Event date:</h4>  <%=u.event_date%>

 <h4>Event description:</h4> <%=u.description%>

  <br>
  <br>
  <br>

<% end %>


<h1>Past Events</h1>

<% @event.previous_events.each do |p| %>

<h4>Event host :</h4> <%=p.creator.name%>

<h4>Event date:</h4>  <%=p.event_date%>

 <h4>Event description:</h4> <%=p.description%>

  <br>
  <br>
  <br>

<% end %>

app/views/events/new.html.erb
<%= form_for(@event,url:new_event_path)do |f| %>
   <%= f.label :event_date %>
  <%= f.date_select :event_date %> <br>

   <%= f.label :description %>
    <%= f.text_field :description, :required => 'required'%> <br>
  <%= f.submit %>


<% end %>

app/views/events/show.html.erb
<h1>Event organizer:<%=@event.creator.name%></h1>


<h1>Event attendees</h1>

<%@event.attendees.each do |e|%>
<li><%=e.name%></li>


<br>
<br>
<br>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>

     <%= f.label :name %>
     <%= f.text_field :name, class: 'form-control' %> <br>

     <%= f.label :password %>
     <%= f.password_field :password, class: 'form-control' %> <br>

     <%= f.label :password_confirmation %>
     <%= f.password_field :password_confirmation, class: 'form-control' %>


     <%= f.submit "Sign up", class: "btn btn-primary" %>
   <% end %>

<p><%= link_to "Home", root_path %></p>

app/views/users/show.html.erb
<h1><%=@user.name%>'s events</h1> <p><%= link_to "Home", root_path %></p> <p><%= link_to "New Event", new_event_path %></p>

<h3>Upcoming events</h3>

<%@upcoming_events.each do |u|%>

<h4>Event date:</h4>  <%=u.event_date%>

 <h4>Event description:</h4> <%=u.description%>

  <br>
  <br>
  <br>
<% end %>


<h3>Previous events</h3>

<%@previous_events.each do |f|%>

<h4>Event date:</h4>  <%=f.event_date%>

 <h4>Event description:</h4> <%=f.description%>

  <br>
  <br>
  <br>
<% end %>



<h1>Events <%=@user.name%> is attending</h1>

<%@user.attended_events.each do |e|%>

<h4>Event date:</h4>  <%=e.event_date%>

 <h4>Event description:</h4> <%=e.description%>

  <br>
  <br>
  <br>

<% end %>




<%= link_to 'Log out', logout_path, method: :delete,data: { confirm: 'Are you sure?' } %>